name: reinvent-scaffold-decorator
channels:
  - pytorch
  - defaults
  - rdkit
  - conda-forge
dependencies:
  - python=3.6
  - rdkit=2019.09.3.0
  - pytorch=1.4
  - cudatoolkit=10.1
  - tqdm
  - scipy
  - matplotlib
  - pyspark=2.4
  - pandas
  - pip
  - pip:
    - future
    - tensorboard